quarkus.datasource.db-kind=postgresql

quarkus.hibernate-orm.schema-management.strategy=drop-and-create
quarkus.hibernate-orm.log.sql=true

%dev.quarkus.datasource.devservices.enabled=true
%dev.quarkus.kafka.devservices.enabled=true
mp.jwt.verify.issuer=api-produtos
mp.messaging.outgoing.estoque-baixo-out.connector=smallrye-kafka
mp.messaging.outgoing.estoque-baixo-out.topic=estoque-baixo
mp.messaging.outgoing.estoque-baixo-out.value.serializer=org.apache.kafka.common.serialization.StringSerializer

mp.messaging.incoming.estoque-baixo-in.connector=smallrye-kafka
mp.messaging.incoming.estoque-baixo-in.topic=estoque-baixo
mp.messaging.incoming.estoque-baixo-in.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer